api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.v1 import views as v1
from .views import get_materials, get_courses, get_quizze
router = routers.DefaultRouter()

router.register("courses", v1.CourseViewset)
router.register("blogs", v1.BlogPageViewset)
router.register("materials", v1.MaterialViewset)
router.register("department", v1.DepartmentViewset)
router.register("past-questions", v1.PassQViewset)


urlpatterns = [
     path('', include(router.urls, namespace='')),
     path('beta/materials/', get_materials),
     path('beta/courses/', get_courses),
     path('beta/quizze/', get_quizze),
     path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

reader/urls.py
from django.urls import path
from . import views

app_name = 'reader'
urlpatterns = [
  path('', views.index, name='index'),
  path('new/', views.new, name='new'),
  path('edit/<int:content_id>/', views.edit, name='edit'),
  path('edit/title/<int:id>/', views.edit_title, name='edit-title'),
  path('snippets/', views.snippet, name='snippet'),
  path('update_book/<section_id>/<block>/', views.update_book, name='update_book'),
  ]

reader/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


# Base model for content types
class Content(models.Model):
  content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
  object_id = models.PositiveIntegerField()
  content_object = GenericForeignKey('content_type', 'object_id')
  
  @property
  def edit_template(self):
    return self.content_object.edit_template()

class BaseContent(models.Model):
    class Meta:
        abstract = True

    def __str__(self):
        return self.get_display_name()

    def get_display_name(self):
        raise NotImplementedError("Subclasses must implement this method.")


# Define models for different types of content
class TextContent(BaseContent):
    text = models.TextField()

    def get_display_name(self):
        return self.text[:50]  # Return first 50 characters of the text
    
    def get_content(self):
      return self.text
      
    def edit_template(self):
      return 'text_edit.html'

class ImageContent(BaseContent):
    image = models.FileField(upload_to='images/')
    caption = models.CharField(max_length=255, blank=True, null=True)
    
    width = models.IntegerField(default=200)
    height = models.IntegerField(default=200)
    gravity = models.CharField(max_length=20, default='start')
    def get_display_name(self):
        return self.caption or "Image"
        
    def get_content(self):
      return f'''<div class='d-flex flex-column justify-content-{self.gravity}'>
            <img width='{self.width}' height='{self.height}' style='object-fit:contain' src="{self.image.url}">
            <p>{self.caption}</p>
          </div>'''


class VideoContent(BaseContent):
    video_url = models.URLField()
    description = models.CharField(max_length=255, blank=True, null=True)
    
    def get_content(self):
      return f'<div><video style="width:100%" src="{self.video_url}" controls /><p>{self.description}</p></div>'

    
    
    def get_display_name(self):
        return self.description or "Video"


class ListContent(BaseContent):
    items = models.TextField(help_text="Enter items as a comma-separated list")

    def get_display_name(self):
        return self.items[:50]  # Return first 50 characters of the list


class LinkContent(BaseContent):
    url = models.URLField()
    title = models.CharField(max_length=255)

    def get_display_name(self):
        return self.title
    def get_content(self):
      return f'<a href="{self.url}">{self.title}</a>'


class BookSubSection(models.Model):
    title = models.CharField(max_length=255)
    contents = models.ManyToManyField(Content)


    
    def __str__(self):
        return self.title


class BookSection(models.Model):
    title = models.CharField(max_length=255)
    subsections = models.ManyToManyField(BookSubSection, related_name='sections')
    contents = models.ManyToManyField(Content)

    def __str__(self):
        return self.title
        
      
class Book(models.Model):
    title = models.CharField(max_length=255)
    sections = models.ManyToManyField(BookSection, related_name='books', blank=True)

    def headers(self):
        """Return a list of all section and subsection titles in the book."""
        headers = []
        for section in self.sections.all():
            headers.append(section.title)
            for subsection in section.subsections.all():
                headers.append(subsection.title)
        return headers

    def __str__(self):
        return self.title

reader/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book, TextContent, Content, BookSubSection, BookSection, ImageContent, LinkContent, VideoContent
# Create your views here.

def index(request):
  return render(request, 'reader/index.html')

def new(request):
  book = Book.objects.first()
  last_section = book.sections.last()
  
  
  return render(request, 'reader/reader.html', {'book': book})

def edit(request, content_id):
  content = Content.objects.get(id=content_id)
  
  if request.method == 'POST':
    text = request.POST.get('text')
    if len(text) > 0:
      content.content_object.text = text
      content.content_object.save()
      return render(request, f'reader/reader.html#text-content', {'content': content})
    else:
      content.content_object.delete()
      content.delete()
      return HttpResponse('Deleted')
  
  return render(request, f'reader/edit/{content.edit_template}', {'content': content})

def edit_title(request, id):
  context = {}
  subsection = request.GET.get('subsection', None)
  if subsection:
    content = BookSubSection.objects.get(id=id)
    context['sub'] = True
  else:
    content = BookSection.objects.get(id=id)
  context['content'] = content
  if request.method == 'POST':
    text = request.POST.get('title')
    if len(text) > 0:
      c = {}
      content.title = text
      content.save()
      if subsection:
        c['subsection'] = content
        v = 'sub-topic'
      else:
        c['section'] = content
        v = 'topic'
      return render(request, f'reader/reader.html#{v}', c)
    else:
      content.delete()
      return HttpResponse(status=204)
  
  return render(request, f'reader/edit/edit_title.html', context)

def update_book(request, section_id, block):
  book = Book.objects.first()
  title = None
  stitle = None
  
  if block == 'section':
    section = book.sections.get(id=int(section_id))
    stitle = request.POST.get('stitle', None)
    title = request.POST.get('title', None)
    pass
  else:
    section = BookSubSection.objects.get(id=int(section_id))
  if request.method == 'POST':
    text = request.POST.get('text', None)
    image = request.FILES.get('image', None)
    link = request.POST.get('link', None)
    video = request.POST.get('video', None)
    
    if title:
      book.sections.create(title=title)
      return HttpResponse(f'<h2>{title}<h2/>')

    if stitle:
      # book.sections.create(title=title)
      
      section.subsections.create(title=stitle)
      
    if text:
      
      text_content = TextContent.objects.create(text=text)
      content = Content.objects.create(content_object=text_content)
      
      section.contents.add(content)
    
    if image:
      caption = request.POST.get('caption', '')
      width = request.POST.get('width', 200)
      height = request.POST.get('height', 200)
      gravity = request.POST.get('gravity', 'center')
      image_content = ImageContent.objects.create(image=image, caption=caption, gravity=gravity, width=width, height=height)
      content = Content.objects.create(content_object=image_content)
      section.contents.add(content)
    if link:
      name = request.POST.get('name')
      link_content = LinkContent.objects.create(url=link, title=name)
      content = Content.objects.create(content_object=link_content)
      section.contents.add(content)
    if video:
      description = request.POST.get('description')
      video_content = VideoContent.objects.create(video_url=video, description=description)
      content = Content.objects.create(content_object=video_content)
      section.contents.add(content)
  if block == 'section':
    return render(request, 'reader/reader.html#section', {'section': section})
  else:
    return render(request, 'reader/reader.html#subsection', {'subsection': section})

def snippet(request):
  type = request.GET.get('type', None)
  block = request.GET.get('block', None)
  id = request.GET.get('id', None)
  context = {'block': block, 'id': id}
  
  return render(request, f'reader/snippet/{type}.html', context)

templates/reader/index.html
{% extends 'base.html' %}

{% block content %}
{% endblock content %}

templates/reader/reader.html
{% extends 'base.html' %}
{% load static %}
{% load partials %}

{% partialdef subsection %}
  <div id="content-subsection-{{ subsection.id }}" class="content-subsection my-2">
    <div class="d-flex flex-row justify-content-between align-items-center">
    {% partialdef sub-topic inline %}
    <h4 id="title-subsection-{{ subsection.id }}" class="d-flex flex-row justify-content-between"
    hx-on:click="
        document.querySelectorAll('.form-wrapper').forEach(el => el.classList.add('d-none'));
        document.querySelectorAll('div').forEach(el => el.classList.remove('active-section'));
        document.getElementById('form-wrapper-sub-{{ subsection.id }}').classList.remove('d-none');
        
        document.getElementById('content-subsection-{{ subsection.id }}').classList.add('active-section')
        ">
      - {{ subsection.title }}
      
    </h4>
    {% endpartialdef %}
    <a
    hx-get='{% url 'reader:edit-title' subsection.id %}?subsection=1'
    hx-target='#title-subsection-{{ subsection.id }}'
    hx-swap="outerHTML"
    hx-trigger="click"
    ><em class="icon ni ni-edit"></em></a>
    </div>
    {% for content in subsection.contents.all %}
      {% partial text-content %}
    {% endfor %}
     <div id="form-wrapper-sub-{{ subsection.id }}" class="form-wrapper d-none">
    
    <div id="form-sub-con-{{ subsection.id }}" class="form-con p-2"></div>
    
    <!-- Form to fetch dynamic content -->
    <form id="form-sub{{ section.id }}" hx-get="{% url 'reader:snippet' %}?block=subsection&id={{subsection.id}}" 
          hx-target="#form-sub-con-{{ subsection.id }}" 
          hx-swap="innerHTML" 
          class="form d-flex flex-row p-2" 
          style="gap: 5px">
      
      <select name="type" class="form-select js-select2">
        <option value="text">Text - Body</option>
        <option value="image">Image</option>
        <option value="video">Video</option>
        <option value="link">Link</option>
      </select>
      
      <button class="btn btn-primary">Add</button>
    </form>
  </div>
    </div>
{% endpartialdef %}

{% partialdef section %}
<div id="content-section-{{ section.id }}" class="py-3 my-2 border-bottom content">
  <div class="d-flex flex-row justify-content-between align-items-center">
  {% partialdef topic inline %}
  <h2 id="title-section-{{ section.id }}" class="d-flex flex-row justify-content-between"
    hx-on:click="
        document.querySelectorAll('div').forEach(el => el.classList.remove('active-section'));
        document.getElementById('content-section-{{ section.id }}').classList.add('active-section')
       
        document.querySelectorAll('.form-wrapper').forEach(el => el.classList.add('d-none'));
        document.getElementById('form-wrapper-{{ section.id }}').classList.remove('d-none');">
    {{ section.title }} 
  </h2>
  {% endpartialdef %}
    <a
    hx-get='{% url 'reader:edit-title' section.id %}'
    hx-target='#title-section-{{ section.id }}'
    hx-swap="outerHTML"
    hx-trigger="click"
    ><em class="icon ni ni-edit"></em></a>
  </div>
  {% for content in section.contents.all %}
  {% partialdef text-content inline %}
    <p
      hx-get='{% url 'reader:edit' content.id %}'
      hx-trigger='click'
      hx-swap='outerHTML'
    >{{ content.content_object.get_content|safe }}</p>
  {% endpartialdef %}
  {% endfor %}
  
  {% for subsection in section.subsections.all %}
    {% partial subsection %}
  {% endfor %}
<div id="form-wrapper-{{ section.id }}" class="form-wrapper d-none">
    <div id="form-con-{{ section.id }}" class="form-con p-2"></div>

    <!-- Form to fetch dynamic content -->
    <form id="form-{{ section.id }}" hx-get="{% url 'reader:snippet' %}?block=section&id={{section.id}}" 
          hx-target="#form-con-{{ section.id }}" 
          hx-swap="innerHTML" 
          class="form d-flex flex-row p-2" 
          style="gap: 5px">
      
      <select name="type" class="form-select js-select2">
        <option value="text-title">New Topic</option>
        <option value="text-subtitle">Sub Topic</option>
        <option value="text">Text - Body</option>
        <option value="image">Image</option>
        <option value="video">Video</option>
        <option value="link">Link</option>
      </select>
      
      <button class="btn btn-primary">Add</button>
    </form>
  </div>
</div>
  <!-- Form container (unique ID for each section) -->
{% endpartialdef %}

{% block content %}
<style>
  .active-section{
    border: .5px solid;
    padding: 3px;
    border-radius: 4px;
  }
</style>
<div class="card border w-auto">
  <div class="d-flex flex-row p-2 border-bottom">
    <img style="width: 50px" src="{% static pr_small_logo %}">
    <p>Reader</p>
  </div>
  
  <div id="content" class="p-2">
    {% for section in book.sections.all %}
      {% partial section %}
    {% endfor %}
  </div>

</div>
{% endblock content %}