api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.v1 import views as v1
from .views import get_materials, get_courses, get_quizze
router = routers.DefaultRouter()

router.register("courses", v1.CourseViewset)
router.register("blogs", v1.BlogPageViewset)
router.register("materials", v1.MaterialViewset)
router.register("department", v1.DepartmentViewset)
router.register("past-questions", v1.PassQViewset)


urlpatterns = [
     path('', include(router.urls, namespace='')),
     path('beta/materials/', get_materials),
     path('beta/courses/', get_courses),
     path('beta/quizze/', get_quizze),
     path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
  path('', views.index, name='index'),
  path('read/<slug:slug>/', views.view_blog, name='read_blog'),
  path('comment/<int:page_id>/', views.comment_blog, name='comment'),
  path('admin/page/<slug:slug>/edit/', views.edit_blog, name='edit_blog'),
  path('admin/pages/', views.blog_list, name='blog_list'),
  path('admin/pages/new', views.add_blog, name='add_blog'),
  path('admin/media/', views.media_gallery, name='media'),
  path('admin/media/add/', views.add_media_gallery, name='add_media'),
  path('admin/media/update/<int:doc_id>/', views.update_media_gallery, name='update_media'),
  ]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
# Create your models here.
class Document(models.Model):
  file = models.FileField(upload_to='documents')
  name = models.CharField(max_length=50)
  alt_text = models.CharField(max_length=50)
  

class Tag(models.Model):
  value = models.CharField(max_length=25)
  pass

class BloggerSite(models.Model):
  owner = models.ForeignKey(User, on_delete=models.CASCADE)
  pages = models.ManyToManyField('BlogPage', blank=True)
  documents = models.ManyToManyField('Document', blank=True)
  name = models.CharField(max_length=50)
  tags = models.ManyToManyField('Tag', blank=True)


class BlogPage(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  title = models.CharField(max_length=500)
  slug = models.CharField(max_length=500)
  summary = models.TextField()
  content = models.TextField()
  cover_image = models.ForeignKey(Document, on_delete=models.SET_NULL, null=True, blank=True, related_name='covers')
  gallery_images = models.ManyToManyField('Document', blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  modified_on = models.DateTimeField(auto_now=True)
  
  next_page = models.OneToOneField('BlogPage', on_delete=models.SET_NULL, null=True, related_name='next', blank=True)
  previous_page = models.OneToOneField('BlogPage', on_delete=models.SET_NULL, null=True, related_name='previous', blank=True)
  
  
  childrens = models.ManyToManyField('BlogPage', blank=True, related_name='parents')
  tags = models.ManyToManyField('Tag', blank=True, related_name='blogs')
  
  allow_comment = models.BooleanField(default=False)
  is_publish = models.BooleanField(default=False)
  
  def save(self, *args, **kwargs):
    if self.slug == '':
      self.slug = slugify(self.title)
    return super(BlogPage, self).save(*args, **kwargs)
  
  def parent(self):
    if BlogPage.objects.filter(childrens__contains=self).exists():
      return BlogPage.objects.filter(childrens__contains=self)[0]
    return None
    
  def get_absolute_url(self):
    return reverse('blog:read_blog', kwargs={'slug':self.slug})

class BlogComment(models.Model):
  blog = models.ForeignKey(BlogPage, on_delete=models.CASCADE, related_name='comments')
  
  name = models.CharField(max_length=50)
  email = models.CharField(max_length=50)
  content = models.TextField()
  
  created_on = models.DateTimeField(auto_now_add=True)
  
  upvote = models.IntegerField(default=0)
  downvote = models.IntegerField(default=0)

blog/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from .models import BlogPage, BloggerSite, Document, Tag, BlogComment
# Create your views here.
def index(request):
  q = request.GET.get('q', '')
  blogs = BlogPage.objects.filter(Q(title__icontains=q)|Q(content__icontains=q),is_publish=True)
  
  return render(request, 'blog/blog_index_page.html', {'blogs': blogs, 'q': q})
def blog_list(request):
  blogs = BlogPage.objects.all()
  return render(request, 'blog/post-list.html', {'blogs': blogs})

def view_blog(request, slug):
  context = {}
  page = BlogPage.objects.get(slug=slug)
  context['page'] = page
  return render(request, 'blog/blog.html', context)


def edit_blog(request, slug):
  context = {}
  blog_site, _ = BloggerSite.objects.get_or_create(owner=request.user)
  tags = Tag.objects.all()
  blog = BlogPage.objects.get(slug=slug)
  pages = BlogPage.objects.all()
  context['documents'] = blog_site.documents
  context['blog'] = blog
  context['tags'] = tags
  context['pages'] = pages
  if request.method == "POST":
    data = request.POST
    title = data.get('title')
    content = data.get('content')
    cover = data.get('cover_image')
    
    allow_comment = data.get('allow_comment', False)
    save_as_draft = data.get('draft', False)
    
    galleries = data.getlist('galleries')
    tag_ids = data.getlist('tags')
    
    _tags = tags.filter(id__in=tag_ids)
    documents = blog_site.documents.filter(id__in=galleries)
    cover_image = blog_site.documents.get(id=cover)
    blog.cover_image = cover_image
    blog.title = title
    blog.content = content
    blog.allow_comment = True if allow_comment else False
    blog.is_publish = False if save_as_draft else True
    blog.gallery_images.clear()
    for doc in documents:
      blog.gallery_images.add(doc)
    blog.tags.clear()
    for tag in _tags:
      blog.tags.add(tag)
    
    blog.save()
  return render(request, 'blog/edit-blog.html', context)

def add_blog(request):
  context = {}
  blog_site, _ = BloggerSite.objects.get_or_create(owner=request.user)
  tags = Tag.objects.all()
  pages = BlogPage.objects.all()
  context['documents'] = blog_site.documents
  context['tags'] = tags
  context['pages'] = pages
  if request.method == "POST":
    data = request.POST
    title = data.get('title')
    content = data.get('content')
    cover = data.get('cover_image')
    
    allow_comment = data.get('allow_comment')
    save_as_draft = data.get('draft')
    
    galleries = data.getlist('galleries')
    tag_ids = data.getlist('tags')
    
    _tags = tags.filter(id__in=tag_ids)
    documents = blog_site.documents.filter(id__in=galleries)
    cover_image = blog_site.documents.get(id=cover)
    blog = BlogPage.objects.create(title=title, content=content, author=request.user, cover_image=cover_image)
    
    if allow_comment:
      blog.allow_comment = True
    if save_as_draft:
      blog.is_publish = False
    
    for doc in documents:
      blog.gallery_images.add(doc)
    for tag in _tags:
      blog.tags.add(tag)
    
    blog.save()
  return render(request, 'blog/page-add.html', context)

def comment_blog(request, page_id):
  page = BlogPage.objects.get(id=page_id)
  if request.method == 'POST':
    name = request.POST.get('name', '')
    email = request.POST.get('email', '')
    content = request.POST.get('content', '')
    BlogComment.objects.create(blog=page, name=name, email=email, content=content)
  return redirect('blog:read_blog', page.slug)

def media_gallery(request):
  context = {}
  blog_site, _ = BloggerSite.objects.get_or_create(owner=request.user)
  context['documents'] = blog_site.documents
  return render(request, 'blog/media.html', context)

def add_media_gallery(request):
  if request.method == 'POST':
    name = request.POST.get('name')
    alt_text = request.POST.get('alt_text')
    document = request.FILES.get('document')
    blog_site, _ = BloggerSite.objects.get_or_create(owner=request.user)
    doc = Document.objects.create(name=name, alt_text=alt_text, file=document)
    blog_site.documents.add(doc)
    blog_site.save()
  return redirect('blog:media')

def update_media_gallery(request, doc_id):
  if request.method == 'POST':
    name = request.POST.get('name')
    alt_text = request.POST.get('alt_text')
    document = request.FILES.get('document')
    blog_site, _ = BloggerSite.objects.get_or_create(owner=request.user)
    if blog_site.documents.filter(id=doc_id).exists():
      doc = blog_site.documents.get(id=doc_id)
      doc.name=name
      doc.alt_text=alt_text
      if document:
        doc.file = document
      doc.save()
  return redirect('blog:media')

templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}


{% block content %}  
<style>
  .custommark{
    border: .5px solid red;
  }
  .body li{
    list-style: auto;
    margin-left: 1rem;
  }
  .body img{
    object-fit: contain;
    height: fit-content;
    border: .5px solid lightgray
    ;
  }
  .cover-img{
    object-fit: contain;
    width: 100%;
    height: 250px;
    margin-bottom: 5px;
  }
  .gallery_image{
    height: 200px !important;
    width: 100%;
    object-fit: contain;
  }
</style>
                <!-- content @s -->
                <div class="nk-content container-fluid">
                    <div class="nk-block-head nk-block-head">
                      <div class="nk-block-between position-relative">
                        <div class="nk-block-head-content">
                                                    <a class="h4" href="{% url 'blog:index' %}"><em class="ni icon ni-arrow-left"></em> Back</a>
                                                </div>
                        <div class="nk-block-head-content">
                                                    <ul class="nk-block-tools g-1">
                                                        <li class="d-lg-none">
                                                            <a href="#" class="btn btn-trigger btn-icon search-toggle toggle-search" data-target="search"><em class="icon ni ni-search"></em></a>
                                                        </li>
                                                      </ul>
                                                <div class="search-wrap px-2 d-lg-none" data-search="search">
                                                    <form text-lookup-form class="search-content">
                                                        <a href="#" class="search-back btn btn-icon toggle-search" data-target="search"><em class="icon ni ni-arrow-left"></em></a>
                                                        <input id="lookup-text" type="text" class="form-control border-transparent form-focus-none" placeholder="Search word or texts">
                                                        <button class="search-submit btn btn-icon"><em class="icon ni ni-search"></em></button>
                                                    </form>
                                                </div><!-- .search-wrap -->
                                            </li>
                                        </div>
                      </div>
                    </div>
                    <div class="container-fluid bg-white">
                    <img class="cover-img mt-1" src="{{ page.cover_image.file.url }}">
                        <div class="nk-content-inner">
                            <div class="nk-content-body">
                                <div class="content-page wide-md m-auto">
                                    <div class="nk-block-head mx-auto">
                                        <a href="html/user-details-regular.html">
                                          <div class="user-card d-flex flex-row">
                                           <div class="user-avatar">
                                             <span>{{page.author.first_name.0}}{{page.author.last_name.0}}</span>
                                           </div>
                                           <div class="user-info">
                                              <span class="text-dark fw-bold">{{ page.author.get_full_name }} {% if user == page.author %}<a href="{% url 'blog:edit_blog' page.slug %}">Edit</a>{% endif %}</span>
                                              <span class="d-block small">Posted on {{ page.created_at|date:'D, M Y H i' }}, Edited on {{ page.modified_on|date:'D, M Y h i' }}</span>
                                            </div>
                                          </div>
                                        </a>
                                        <div class="nk-block-head-content mt-2">
                                          {% for tag in page.tags.all %}
                                          <span class="badge bg-outline-{% cycle 'primary' 'secondary' 'dark' %}">{{ tag.value }}</span>
                                          {% endfor %}
                                            <h2 class="nk-block-title fw-bold mt-1">{{ page.title }}</h2>
                                        </div>
                                    </div><!-- .nk-block-head -->
                                    <div class="nk-block">
                                        <div class="card">
                                            <div class="card-inner card-inner-xl p-1">
                                                <article class="entry body">
                                                    <div id="content">
                                                    {{ page.content|safe }}
                                                    </div>
                                                    {% if page.gallery_images.all %}
                                                    <div id="carouselExConInd" class="carousel carousel-fade border" data-bs-ride="carousel">
                                                       <div class="carousel-inner">
                                                        {% for doc in page.gallery_images.all %}
                                                            <a class="carousel-item {% if page.gallery_images.first == doc %}active{% endif %}">
                                                              <img class="gallery_image" src="{{ doc.file.url }}" >
                                                              <span class="border-bottom pb-1">
                                                                  <p class="fst-italic text-center">{{ doc.alt_text }}</p>
                                                                </span>
                                                            </a>
                                                          {% endfor %}
                                                        </div>
                                                        <a class="carousel-control-prev" href="#carouselExConInd" role="button" data-bs-slide="prev">
                                                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                                            <span class="visually-hidden">Previous</span>
                                                        </a>
                                                        <a class="carousel-control-next" href="#carouselExConInd" role="button" data-bs-slide="next">
                                                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                                            <span class="visually-hidden">Next</span>
                                                        </a>
                                                    </div>
                                                    {% endif %}
                                                </article>
                                            </div>
                                        </div><!-- .card -->
                                        <div class="card card-bordered">
                                          {% for comment in page.comments.all %}
                                            <div class="nk-msg-item current" data-msg-id="1">
                                            <div class="nk-msg-media user-avatar">
                                                <span>AL</span>
                                            </div>
                                            <div class="nk-msg-info">
                                                <div class="nk-msg-from">
                                                    <div class="nk-msg-sender">
                                                        <div class="name">{{ comment.name }}</div>
                                                    </div>
                                                    <div class="nk-msg-meta">
                                                        <l<div class="date">{{ comment.created_on }}</l>
                                                    </div>
                                                </div>
                                                <div class="nk-msg-context">
                                                    <div class=" w-75">
                                                      {{ comment.content|safe }}
                                                    </div>
                                                    <div class="nk-msg-lables">
                                                        <div class="small">{{ comment.upvote }} <a href="#"><em class="icon ni ni-upword-ios"></em></a></div>
                                                        <div class="small">{{ comment.downvote }} <a href="#"><em class="icon ni ni-downward-ios"></em></a></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div><!-- .nk-msg-item -->
                                          {% endfor %}
                                        {% if page.allow_comment %}
                                            <div class="card-inner">
                                                <div class="card-head">
                                                    <h5 class="card-title">Leave a Reply</h5>
                                                </div>
                                                <form action="{% url 'blog:comment' page.id %}" method="post" id="blog-form">
                                                    {% csrf_token %}
                                                    <div class="form-group">
                                                        <label class="form-label">Comment</label>
                                                        <div class="form-control-wrap">
                                                            <div id="blogbody" class="summernote-minimal">
                                                                <p>Great!</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label class="form-label" for="cf-full-name">Name</label>
                                                        <input name="name" type="text" class="form-control" id="cf-full-name" value="{{ user.get_full_name }}">
                                                    </div>
                                                    <div class="form-group">
                                                        <label class="form-label" for="cf-email-address">Email</label>
                                                        <input name="email" type="text" class="form-control" id="cf-email-address" value="{{ user.email }}">
                                                    </div>
                                                    <div class="form-group">
                                                        <button type="submit" class="btn btn-primary">Post Comment</button>
                                                    </div>
                                                </form>
                                            </div>
                                        {% else %}
                                        <p>Comment is disabled for this page</p>
                                        {% endif %}
                                        </div>
                                        
                                    </div><!-- .nk-block -->
                                </div><!-- .content-page -->
                            </div>
                        </div>
                    </div>
                </div>
               
                <!-- content @e -->
{% endblock content %}  
{% block script %}  
    <link rel="stylesheet" href="{% static 'css/editors/summernote.css' %}">
    <script src="{% static 'js/libs/editors/summernote.js' %}"></script>
    <script src="{% static 'js/editors.js' %}"></script>
    <script src="{% static 'js/text-lookup.js' %}"></script>
    <script>

      const form_tag = document.getElementById("blog-form"); // Replace 'mail-form' with the actual ID of your form

      function submitFormWithTinyMCEContent() {

        const summernoteContent = $("#blogbody").summernote('code');

        const hiddenInput1 = document.createElement("input");
        
        hiddenInput1.type = "hidden";
        hiddenInput1.name = "content";
        hiddenInput1.value = summernoteContent;
    
        form_tag.appendChild(hiddenInput1);
        form_tag.submit();
}
      // Attach event listener to form submission
     
      form_tag.addEventListener("submit", function (event) {
            event.preventDefault(); // Prevent default form submission
            submitFormWithTinyMCEContent(); // Call function to handle form submission with TinyMCE content
      });
    
    
  
  </script>
{% endblock script %}  

templates/blog/blog_index_page.html
{% extends "base.html" %}

<!-- Load wagtailimages_tags: -->
{% block style %}
{% endblock style %}
{% block content %}
<style>
  .pages{
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    gap: 15px;
    justify-content: center;
  }
  .pages > a{
    width: 350px;
    height: 350px;
    border: 1px solid lightgray;
    position: relative;
  }
  .pages > a > img{
    position: absolute;
    height: 100%;
  }
  .pages > a > div{
    padding: 10px;
    position: absolute;
    bottom: 0px;
    background: linear-gradient(transparent, #000000a8 15%, black 80%);
  }
</style>
<div class="bg-white p-1">
  <div class="nk-block-head nk-block-head">
                      <div class="nk-block-between position-relative">
                        <div class="nk-block-head-content">
                                                    <h3>Pages</h3>
                                                </div>
                        <div class="nk-block-head-content">
                                                    <ul class="nk-block-tools g-1">
                                                        <li class="d-lg-none">
                                                            <a href="#" class="btn btn-trigger btn-icon search-toggle toggle-search" data-target="search"><em class="icon ni ni-search"></em></a>
                                                        </li>
                                                        <li class="d-lg-none">
                                                            <div class="dropdown">
                                                                <a href="#" class="btn btn-trigger btn-icon" data-bs-toggle="dropdown"><em class="icon ni ni-menu-alt-r"></em></a>
                                                                <div class="dropdown-menu dropdown-menu-end">
                                                                    <ul class="link-list-opt no-bdr">
                                                                        <li><a href="{% url 'blog:add_blog' %}" ><em class="icon ni ni-plus"></em><span>Add Page</span></a></li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                
                                                <div class="search-wrap px-2 d-lg-none" data-search="search">
                                                    <form class="search-content">
                                                        <a href="#" class="search-back btn btn-icon toggle-search" data-target="search"><em class="icon ni ni-arrow-left"></em></a>
                                                        <input name="q" type="text" class="form-control border-transparent form-focus-none" placeholder="Search pages">
                                                        <button class="search-submit btn btn-icon"><em class="icon ni ni-search"></em></button>
                                                    </form>
                                                </div><!-- .search-wrap -->
                                            </li>
                                        </div>
                      </div>
                    </div>
    {% if q %}
    <p>All pages that contains {{ q }}</p>
    {% endif %}
  <div class="pages">
    {% for page in blogs %}
      <a href="{% url 'blog:read_blog' page.slug %}" class="rounded">
        <img src="{{ page.cover_image.file.url }}">
        <div>
          <h6 class="p-1 pb-0 text-white">{{page.title|truncatechars:50}}</h6>
          <div class="user-card d-flex flex-row">
                                           <div class="user-avatar">

                                             <span>{{page.author.first_name.0}}{{page.author.last_name.0}}</span>
                                           </div>
                                           <div class="user-info text-white">
                                              <span class="fw-bold">{{ page.author.get_full_name }}</span>
                                              <span class="d-block small">Posted on {{ page.created_at|date:'D, M Y' }}, Edited on {{ page.modified_on|date:'D, M Y' }}</span>
                                            </div>
                                          </div>
        </div>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}

templates/blog/blog_page.html
{% extends "base.html" %}
<!-- Load the wagtailimages_tags: -->
{% load wagtailcore_tags wagtailimages_tags %}

{% block body_class %}template-blogpage{% endblock %}

{% block content %}
<style>
  .body li{
    list-style: initial;
    margin-left: 1rem;
  }
  .body img{
    object-fit: contain;
    height: fit-content;
    border: .5px solid lightgray
    ;
  }
</style>
<div class="bg-white p-1">
    <h1 class="text-center text-primary-emphasis">{{ page.title }}</h1>
    {% with page.main_image as main_image %}
    <div class="center">
        {% if main_image %}{% image main_image fill-300x200 %}{% endif %}
    </div>
    {% endwith %}
    <p class="p-1">{{ page.date }}</p>
    <p class="intro fst-italic p-1 mb-1">{{ page.intro }}</p>
    <p><a href="{{ page.get_parent.url }}"><em class="ni icon ni-chevron-left"></em>Previous Page</a></p>
    <div class="body p-1 fs-4">
    
      {{ page.body|richtext }}

    <!-- Add this: -->
    <div id="carouselExConInd" class="carousel slide border" data-bs-ride="carousel">
     <div class="carousel-inner">
    {% for item in page.gallery_images.all %}
        <a class="carousel-item {% if page.gallery_images.first == item %}active{% endif %}">
          <span class="border-bottom pb-1">
               {% image item.image fill-320x240 %}
              <p class="fst-italic text-center">{{ item.caption }}</p>
            </span>
        </a>
        {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselExConInd" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExConInd" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </a>
</div>
    </div>
    <p><a href="{{ page.get_parent.url }}"><em class="ni icon ni-chevron-left"></em>Previous Page</a></p>
    {% if page.get_children %}
    <p>Sub Pages</p>
      {% for page in page.get_children %}
        <p><a href="{% pageurl page %}">{{page.title}}</a></p>
      {% endfor %}
    {% endif %}
</div>
{% endblock %}

templates/blog/footer.html
<footer>
    <p>Built with Wagtail</p>

    {% with twitter_url=settings.blog.NavigationSettings.twitter_url github_url=settings.blog.NavigationSettings.github_url mastodon_url=settings.blog.NavigationSettings.mastodon_url %}
        {% if twitter_url or github_url or mastodon_url %}
            <p>
                Follow me on:
                {% if github_url %}
                    <a href="{{ github_url }}">GitHub</a>
                {% endif %}
                {% if twitter_url %}
                    <a href="{{ twitter_url }}">Twitter</a>
                {% endif %}
                {% if mastodon_url %}
                    <a href="{{ mastodon_url }}">Mastodon</a>
                {% endif %}
            </p>
        {% endif %}
    {% endwith %}
</footer>

templates/blog/index.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
  <div class="card-header">
    <h3 class="card-title">All Blogs</h3>
  </div>
  <div class="card-body p-1 d-flex flex-row flex-wrap g-2 mt-1 justify-content-around flex-fill">
    {% for blog in blogs %}
      <div style="height:fit-content;width:250px;" class="card mb-1 border d-flex flex-column p-0">
        <img class="card-img-top h-150px object-fit-cover" src="{{blog.cover.url}}">
        <h6 class="card-title p-1 pb-0 text-decoration-underline">{{blog.title|truncatechars:25}}</h6>
        <p class="card-text p-1 pb-0 pt-0">{{blog.desc|truncatechars:100}}</p>
        <div class="card-footer">
          <p class="d-flex justify-content-between">{{blog.ratings.count}} rate <a href="{% url 'blog:read_blog' blog.id %}"><span>Read</span><em class="ni icon ni-arrow-right"></em></a></p>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}